server:
  port: 10010
spring:
  application:
    name: sc-gateway

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** #商品微服务映射路径   服务名item-service：映射路径/item/**   只要是/api/item/**都路由到商品微服务